name: DeLinker
channels:
  - rdkit
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_1100_select=0.0.1=gpu
  - astor-0.5-py36_0.tar.bz2
  - blas-2.113-openblas.tar.bz2
  - bzip2-1.0.8-h7f98852_4.tar.bz2
  - c-ares-1.18.1-hf897c2e_0.tar.bz2
  - ca-certificates-2021.10.8-h1084571_0.tar.bz2
  - cairo-1.16.0-h2e03771_1010.tar.bz2
  - certifi-2021.10.8-py39ha65689a_1.tar.bz2
  - cudatoolkit-11.4.2-h71cc953_10.tar.bz2
  - cudnn-8.2.1-cuda11.3_0.tar.bz2
  - cupti-11.3.1-0.tar.bz2
  - cycler-0.10.0-py36_0.tar.bz2
  - cython-0.29.28-py38h0119ad3_0.tar.bz2
  - dbus-1.13.6-h0f95b14_3.tar.bz2
  - expat-2.4.7-ha18d298_0.tar.bz2
  - fontconfig-2.13.96-h856ede2_2.tar.bz2
  - freetype-2.10.4-h8a70690_1.tar.bz2
  - gast
  - glib-2.70.2-h469bdbd_4.tar.bz2
  - gst-plugins-base
  - gstreamer
  - intel-openmp
  - joblib
  - kiwisolver
  - libboost
  - libedit
  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libprotobuf
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - markdown
  - matplotlib
  - mkl
  - mkl_fft
  - mkl_random
  - ncurses
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pandas
  - pcre
  - pillow
  - pip
  - protobuf
  - py-boost
  - pyparsing
  - pyqt
  - python-dateutil
  - pytz
  - qt
  - scikit-learn
  - scipy
  - sip
  - sqlite
  - tensorboard
  - tensorflow
  - tensorflow-base
  - tensorflow-gpu
  - tk
  - tornado
  - werkzeug
  - xz
  - zlib
  - absl-py
  - docopt
  - setuptools
  - six
  - termcolor
  - typing
  - wheel
  - grpcio
  - icu
  - jpeg
  - libffi
  - pixman
  - python
  - readline
  - rdkit
  - pip:
    - planarity
