name: DeLinker
channels:
  - rdkit
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_1100_select=0.0.1=gpu
  - astor
  - blas
  - bzip2
  - c-ares-
  - ca-certificates
  - cairo
  - certifi
  - cudatoolkit
  - cudnn
  - cupti
  - cycler
  - cython
  - dbus
  - expat
  - fontconfig
  - freetype
  - gast
  - glib
  - gst-plugins-base
  - gstreamer
  - intel-openmp
  - joblib
  - kiwisolver
  - libboost
  - libedit
  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libprotobuf
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - markdown
  - matplotlib
  - mkl
  - mkl_fft
  - mkl_random
  - ncurses
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pandas
  - pcre
  - pillow
  - pip
  - protobuf
  - py-boost
  - pyparsing
  - pyqt
  - python-dateutil
  - pytz
  - qt
  - scikit-learn
  - scipy
  - sip
  - sqlite
  - tensorboard
  - tensorflow
  - tensorflow-base
  - tensorflow-gpu
  - tk
  - tornado
  - werkzeug
  - xz
  - zlib
  - absl-py
  - docopt
  - setuptools
  - six
  - termcolor
  - typing
  - wheel
  - grpcio
  - icu
  - jpeg
  - libffi
  - pixman
  - python
  - readline
  - rdkit
  - pip:
    - planarity
